---
# vars file for agent
env_file_path: /etc/default/jenkins.env
jdk21_deb_download_url: https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
api_url: http://{{ jenkins_master_host }}:{{ jenkins_master_port }}
agent_download_url: "{{api_url}}/jnlpJars/agent.jar"