---
# handlers file for agent
- name: Restart Jenkins Agent
  ansible.builtin.systemd:
    name: "{{ agent.service_name }}"
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Reload Systemd Daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload